name: 🚩 Bugs, Errors, and Other Issues
description: Report an issue to help us improve FF Ultima.
labels:
  - "bug"
  - "issue"
body:
  - type: markdown
    attributes:
      value: |
        ## Before submitting, have you already looked through the [FF Ultima Wiki](https://github.com/soulhotel/FF-ULTIMA/wiki)?

  - type: checkboxes
    id: checked-wiki
    attributes:
      label: ""
      description: "Have you looked at the [FF Ultima Wiki](https://github.com/soulhotel/FF-ULTIMA/wiki)?"
      options:
        - label: "Yes"
          required: false
    validations:
      required: false

  - type: checkboxes
    id: userjs-applied
    attributes:
      label: "First time Install? Do you see this welcome message in about:config?"
      description: "![image](https://github.com/user-attachments/assets/7c3c1fb9-8080-4823-9994-23e6af91498e) <br> If No, follow the install guide [Steps 4-7](https://github.com/soulhotel/FF-ULTIMA/wiki/How-to-Install-the-Theme#installation)"
      options:
        - label: "Yes"
          required: false
    validations:
      required: false

  - type: checkboxes
    id: browser-updated
    attributes:
      label: "Is your Browser updated to the latest version?"
      description: "Is your Browser updated to the latest version?"
      options:
        - label: "Yes"
          required: false
    validations:
      required: false

  - type: checkboxes
    id: platform-browser
    attributes:
      label: "What Browser are you on?"
      description: "Firefox forks are supported, so long as the theme supports the Firefox Version #."
      options:
        - label: "Firefox Default"
          required: false
        - label: "Firefox Nightly"
          required: false
        - label: "Firefox Beta/Developer"
          required: false
        - label: "Librewolf"
          required: false
    validations:
      required: true

  - type: checkboxes
    id: platform-os
    attributes:
      label: "What OS (operating system) are you on?"
      description: "All OS (operating systems) are fully supported. But, testing on Mac is a little limited!"
      options:
        - label: "Windows"
          required: false
        - label: "Linux"
          required: false
        - label: "Mac"
          required: false
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the Issue"
      placeholder: "A detailed description of the issue. Or what you expect to happen."
    validations:
      required: true

  - type: textarea
    id: picture-video
    attributes:
      label: "Picture/Video of the Issue"
      description: "Screenshot(s) or video of the issue are preferred."
      placeholder: "Drag & Drop | Copy & Paste | or Link to Picture & Video"
    validations:
      required: false
