name: 🚩 Bugs, Errors, and Other Issues
description: Report an issue to help us improve FF Ultima.
labels:
  - "bug"
  - "issue"
body:
  - type: markdown
    attributes:
      value: |
        ## Before submitting, have you already looked through the [FF Ultima Wiki](https://github.com/soulhotel/FF-ULTIMA/wiki)?

  - type: dropdown
    id: checked-wiki
    attributes:
      label: "Already looked at the Wiki?"
      description: "[FF Ultima Wiki](https://github.com/soulhotel/FF-ULTIMA/wiki)"
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: userjs-applied
    attributes:
      label: "First time Install? Do you see this message on about:config?"
      description: "Follow installation instructions [Step 4-7](https://github.com/soulhotel/FF-ULTIMA/wiki/How-to-Install-the-Theme#installation)"
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the Issue"
      placeholder: "A detailed description of the issue. Or what you expect to happen."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Platform/Desktop"

  - type: dropdown
    id: platform-os
    attributes:
      label: "Platform/Desktop"
      options:
        - "Windows"
        - "Linux"
        - "Mac"
    validations:
      required: true

  - type: dropdown
    id: platform-browser
    attributes:
      label: "Web Browser"
      options:
        - "Firefox"
        - "Firefox Nightly"
        - "Firefox Dev Edition"
        - "Other Browser"
    validations:
      required: true

  - type: input
    id: other-browser
    attributes:
      label: "If `Other Browser` was selected, specify here:"
      placeholder: "Example: Waterfox v123"
    validations:
      required: false

  - type: dropdown
    id: browser-updated
    attributes:
      label: "Is your browser updated to the latest version?"
      options:
        - "Yes"
        - "No"
    validations:
      required: true
    
  - type: textarea
    id: picture-video
    attributes:
      label: "Picture/Video of the Issue"
      description: "Screenshot(s) or video of the issue are preferred."
      placeholder: "Drag & Drop | Copy & Paste | or Link to Picture & Video"
    validations:
      required: false
